services:
  tidal-dl:
    build:
      dockerfile: ./Dockerfile
    container_name: tidal-dl
    image: tidal-dl-debug
    restart: no
    environment:
      - WEBUI_PORT=5578
      - WEBUI_USER=admin
      - WEBUI_PASS=${TIDALDL_PASS}
      - PUID=${TIDALDL_ID}
      - PGID=${MEDIA_ID}
    ports:
      - "5578:5578/tcp"
    volumes:
      - "./docker-data/data:/data"
      - "./docker-data/music:/music"

